/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */
package ejercicio14.gui.ventanas;

import ejercicio14.logica.ControlEmpleados;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Javier BO
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnResetear = new javax.swing.JButton();
        btnLeerFichero = new javax.swing.JButton();
        btnObtenerEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnResetear.setText("Resetear fichero");
        btnResetear.setToolTipText("Resetea el fichero a sus datos iniciales");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        btnLeerFichero.setText("Leer Fichero");
        btnLeerFichero.setToolTipText("Resetea el fichero a sus datos iniciales");
        btnLeerFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerFicheroActionPerformed(evt);
            }
        });

        btnObtenerEmpleado.setText("Obtener Empleado");
        btnObtenerEmpleado.setToolTipText("Resetea el fichero a sus datos iniciales");
        btnObtenerEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetear, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnLeerFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnObtenerEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnResetear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLeerFichero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObtenerEmpleado)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        ControlEmpleados.resetearFichero();
    }//GEN-LAST:event_btnResetearActionPerformed

    private void btnLeerFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerFicheroActionPerformed
        ControlEmpleados.leerFichero();
    }//GEN-LAST:event_btnLeerFicheroActionPerformed

    private void btnObtenerEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerEmpleadoActionPerformed
        int id = pedirId();
    }//GEN-LAST:event_btnObtenerEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeerFichero;
    private javax.swing.JButton btnObtenerEmpleado;
    private javax.swing.JButton btnResetear;
    // End of variables declaration//GEN-END:variables

    private int pedirId() {
        String id = JOptionPane.showInputDialog(this, "Introduzca la ID del trabajador");
        if (id !=null && id!="")
            try{
            
            }catch(NumberFormatException e){
            JOptionPane.showInputDialog(this, "Introduzca la ID del trabajador");
            }
    }
}
