/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */

package ejercicio15.gui.ventanas;

import ejercicio15.dto.ResultadoOperacion;
import ejercicio15.gui.dialogos.DEmpleado;
import ejercicio15.gui.dialogos.DTrabajo;
import ejercicio15.gui.tablemodels.EmpleadosTableModel;
import ejercicio15.gui.tablemodels.TrabajosTableModel;
import ejercicio15.logica.Control;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jose Javier Bailon Ortiz
 */
public class VPrincipal15 extends javax.swing.JFrame {

    /** Creates new form VPrincipal15 */
    public VPrincipal15() {
        initComponents();
        //enlaza las tablas con los modelos
        inicializarTablas();
    }
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelTrabajos = new javax.swing.JPanel();
        lbTrabajos = new javax.swing.JLabel();
        scrollTrabajos = new javax.swing.JScrollPane();
        tblTrabajosActivos = new javax.swing.JTable();
        lbTrabajosEliminados = new javax.swing.JLabel();
        scrollTrabajosEliminados = new javax.swing.JScrollPane();
        tblTrabajosBorrados = new javax.swing.JTable();
        panelTrabajosOperaciones = new javax.swing.JPanel();
        btnAnadirTrabajo = new javax.swing.JButton();
        btnEditarTrabajo = new javax.swing.JButton();
        btnEliminarTrabajo = new javax.swing.JButton();
        btnVerTrabajo = new javax.swing.JButton();
        btnAsignacionEmpleados = new javax.swing.JButton();
        panelEmpleados = new javax.swing.JPanel();
        lbEmpleados = new javax.swing.JLabel();
        scrollEmpleados = new javax.swing.JScrollPane();
        tblEmpleadosActivos = new javax.swing.JTable();
        lbEmpleadosEliminados = new javax.swing.JLabel();
        scrollEmpleadosEliminados = new javax.swing.JScrollPane();
        tblEmpleadosBorrados = new javax.swing.JTable();
        panelEmpleadosOperaciones = new javax.swing.JPanel();
        btnAnadirEmpleado = new javax.swing.JButton();
        btnEditarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        btnVerEmpleado = new javax.swing.JButton();
        btnAsignacionTrabajos = new javax.swing.JButton();
        panelTrabajo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelEmpleado = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miResetDatosIniciales = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        mTrabajo = new javax.swing.JMenu();
        miVerTodosTrabajos = new javax.swing.JMenuItem();
        miAnadirTrabajo = new javax.swing.JMenuItem();
        miEditarTrabajo = new javax.swing.JMenuItem();
        miEliminarTrabajo = new javax.swing.JMenuItem();
        miVerUnTrabajo = new javax.swing.JMenuItem();
        miAsignarEmpleados = new javax.swing.JMenuItem();
        mEmpleados = new javax.swing.JMenu();
        miVerTodosEmpleados = new javax.swing.JMenuItem();
        miAnadirEmpleado = new javax.swing.JMenuItem();
        miEditarEmpleado = new javax.swing.JMenuItem();
        miEliminarEmpleado = new javax.swing.JMenuItem();
        miVerEmpleado = new javax.swing.JMenuItem();
        miAsignarTrabajos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        lbTrabajos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTrabajos.setText("TRABAJOS");

        tblTrabajosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTrabajos.setViewportView(tblTrabajosActivos);

        lbTrabajosEliminados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTrabajosEliminados.setText("TRABAJOS ELIMINADOS");

        tblTrabajosBorrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTrabajosEliminados.setViewportView(tblTrabajosBorrados);

        panelTrabajosOperaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelTrabajosOperaciones.setPreferredSize(new java.awt.Dimension(183, 500));

        btnAnadirTrabajo.setText("Añadir trabajo");
        btnAnadirTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirTrabajoActionPerformed(evt);
            }
        });

        btnEditarTrabajo.setText("Editar trabajo");

        btnEliminarTrabajo.setText("Eliminar trabajo");

        btnVerTrabajo.setText("Ver trabajo");

        btnAsignacionEmpleados.setText("Asignación de empleados");

        javax.swing.GroupLayout panelTrabajosOperacionesLayout = new javax.swing.GroupLayout(panelTrabajosOperaciones);
        panelTrabajosOperaciones.setLayout(panelTrabajosOperacionesLayout);
        panelTrabajosOperacionesLayout.setHorizontalGroup(
            panelTrabajosOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajosOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrabajosOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerTrabajo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnadirTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignacionEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTrabajosOperacionesLayout.setVerticalGroup(
            panelTrabajosOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajosOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnadirTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignacionEmpleados)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTrabajosLayout = new javax.swing.GroupLayout(panelTrabajos);
        panelTrabajos.setLayout(panelTrabajosLayout);
        panelTrabajosLayout.setHorizontalGroup(
            panelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajosLayout.createSequentialGroup()
                .addGroup(panelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajosLayout.createSequentialGroup()
                        .addGroup(panelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollTrabajosEliminados, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(scrollTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTrabajosOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTrabajosLayout.createSequentialGroup()
                        .addComponent(lbTrabajosEliminados)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelTrabajosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTrabajos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTrabajosLayout.setVerticalGroup(
            panelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTrabajos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelTrabajosLayout.createSequentialGroup()
                        .addComponent(panelTrabajosOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTrabajosEliminados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTrabajosEliminados, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelTrabajos, "panelTrabajos");

        lbEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEmpleados.setText("EMPLEADOS");

        tblEmpleadosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollEmpleados.setViewportView(tblEmpleadosActivos);

        lbEmpleadosEliminados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEmpleadosEliminados.setText("EMPLEADOS ELIMINADOS");

        tblEmpleadosBorrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollEmpleadosEliminados.setViewportView(tblEmpleadosBorrados);

        panelEmpleadosOperaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelEmpleadosOperaciones.setPreferredSize(new java.awt.Dimension(183, 500));

        btnAnadirEmpleado.setText("Añadir empleado");
        btnAnadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirEmpleadoActionPerformed(evt);
            }
        });

        btnEditarEmpleado.setText("Editar empleado");

        btnEliminarEmpleado.setText("Eliminar empleado");

        btnVerEmpleado.setText("Ver empleado");

        btnAsignacionTrabajos.setText("Asignación de trabajos");

        javax.swing.GroupLayout panelEmpleadosOperacionesLayout = new javax.swing.GroupLayout(panelEmpleadosOperaciones);
        panelEmpleadosOperaciones.setLayout(panelEmpleadosOperacionesLayout);
        panelEmpleadosOperacionesLayout.setHorizontalGroup(
            panelEmpleadosOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadosOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnadirEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignacionTrabajos, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEmpleadosOperacionesLayout.setVerticalGroup(
            panelEmpleadosOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnadirEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignacionTrabajos)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollEmpleadosEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(scrollEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEmpleadosOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmpleados)
                            .addComponent(lbEmpleadosEliminados))
                        .addGap(0, 397, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEmpleadosOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmpleadosEliminados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollEmpleadosEliminados, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelEmpleados, "panelEmpleados");

        jLabel1.setText("trabajo");

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajoLayout.createSequentialGroup()
                .addContainerGap(493, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelTrabajo, "card4");

        javax.swing.GroupLayout panelEmpleadoLayout = new javax.swing.GroupLayout(panelEmpleado);
        panelEmpleado.setLayout(panelEmpleadoLayout);
        panelEmpleadoLayout.setHorizontalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        panelEmpleadoLayout.setVerticalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelEmpleado, "panelEmpleado");

        mArchivo.setText("Archivo");

        miResetDatosIniciales.setText("Reset a datos iniciales");
        miResetDatosIniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miResetDatosInicialesActionPerformed(evt);
            }
        });
        mArchivo.add(miResetDatosIniciales);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mArchivo.add(miSalir);

        barraMenu.add(mArchivo);

        mTrabajo.setText("Trabajos");

        miVerTodosTrabajos.setText("Ver todos los trabajos");
        miVerTodosTrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerTodosTrabajosActionPerformed(evt);
            }
        });
        mTrabajo.add(miVerTodosTrabajos);

        miAnadirTrabajo.setText("Añadir trabajo");
        miAnadirTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnadirTrabajoActionPerformed(evt);
            }
        });
        mTrabajo.add(miAnadirTrabajo);

        miEditarTrabajo.setText("Editar trabajo...");
        mTrabajo.add(miEditarTrabajo);

        miEliminarTrabajo.setText("Eliminar trabajo...");
        miEliminarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEliminarTrabajoActionPerformed(evt);
            }
        });
        mTrabajo.add(miEliminarTrabajo);

        miVerUnTrabajo.setText("Ver trabajo...");
        miVerUnTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerUnTrabajoActionPerformed(evt);
            }
        });
        mTrabajo.add(miVerUnTrabajo);

        miAsignarEmpleados.setText("Asignación de empleados a trabajo...");
        mTrabajo.add(miAsignarEmpleados);

        barraMenu.add(mTrabajo);

        mEmpleados.setText("Empleados");

        miVerTodosEmpleados.setText("Ver todos los empleados");
        miVerTodosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerTodosEmpleadosActionPerformed(evt);
            }
        });
        mEmpleados.add(miVerTodosEmpleados);

        miAnadirEmpleado.setText("Añadir empleado");
        miAnadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnadirEmpleadoActionPerformed(evt);
            }
        });
        mEmpleados.add(miAnadirEmpleado);

        miEditarEmpleado.setText("Editar empleado...");
        mEmpleados.add(miEditarEmpleado);

        miEliminarEmpleado.setText("Eliminar empleado...");
        miEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEliminarEmpleadoActionPerformed(evt);
            }
        });
        mEmpleados.add(miEliminarEmpleado);

        miVerEmpleado.setText("Ver empleado...");
        mEmpleados.add(miVerEmpleado);

        miAsignarTrabajos.setText("Asignación de trabajos a empleado...");
        mEmpleados.add(miAsignarTrabajos);

        barraMenu.add(mEmpleados);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Desea salir?","Salir del programa",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miVerUnTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerUnTrabajoActionPerformed
       
    }//GEN-LAST:event_miVerUnTrabajoActionPerformed

    private void miVerTodosTrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerTodosTrabajosActionPerformed
        verPanel("panelTrabajos");
    }//GEN-LAST:event_miVerTodosTrabajosActionPerformed

    private void miResetDatosInicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miResetDatosInicialesActionPerformed
        int r = JOptionPane.showConfirmDialog(this, "¿Desea cargar los datos del archivo de texto? Se borrarán los datos actuales","Reset de datos iniciales", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (r==JOptionPane.YES_OPTION){
            Control.resetDatosIniciales();
            actualizarTablas();
        }
    }//GEN-LAST:event_miResetDatosInicialesActionPerformed

    private void miVerTodosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerTodosEmpleadosActionPerformed
         verPanel("panelEmpleados");
    }//GEN-LAST:event_miVerTodosEmpleadosActionPerformed

    private void miAnadirTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnadirTrabajoActionPerformed
        DTrabajo dt=new DTrabajo(this,true,null,DTrabajo.Tipo.CREAR);
        dt.setLocationRelativeTo(this);
        dt.setVisible(true);
        actualizarTablas();
    }//GEN-LAST:event_miAnadirTrabajoActionPerformed

    private void btnAnadirTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirTrabajoActionPerformed
        DTrabajo dt=new DTrabajo(this,true,null,DTrabajo.Tipo.CREAR);
        dt.setLocationRelativeTo(this);
        dt.setVisible(true);
        actualizarTablas();
    }//GEN-LAST:event_btnAnadirTrabajoActionPerformed

    private void btnAnadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirEmpleadoActionPerformed
        DEmpleado dt=new DEmpleado(this,true,null,DEmpleado.Tipo.CREAR);
        dt.setLocationRelativeTo(this);
        dt.setVisible(true);
        actualizarTablas();
    }//GEN-LAST:event_btnAnadirEmpleadoActionPerformed

    private void miAnadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnadirEmpleadoActionPerformed
        DEmpleado dt=new DEmpleado(this,true,null,DEmpleado.Tipo.CREAR);
        dt.setLocationRelativeTo(this);
        dt.setVisible(true);
        actualizarTablas();
    }//GEN-LAST:event_miAnadirEmpleadoActionPerformed

    private void miEliminarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEliminarTrabajoActionPerformed
        int id=0;
        boolean recogido=false;
        while(!recogido){
            String idSt = JOptionPane.showInputDialog(this, "Escriba la ID del trabajo", "Eliminar trabajo", JOptionPane.PLAIN_MESSAGE);
            if (idSt==null)
                return;
            try{
            id = Integer.parseInt(idSt);
            recogido=true;
            }catch(NumberFormatException ex){
            }
        }
        ResultadoOperacion r = Control.eliminarTrabajo(id);
        if (r.isOk()){
                JOptionPane.showMessageDialog(this, "Trabajo eliminado", "", JOptionPane.PLAIN_MESSAGE);
                actualizarTablas();
        }
        else{
                JOptionPane.showMessageDialog(this, r.getMsg(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_miEliminarTrabajoActionPerformed

    private void miEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEliminarEmpleadoActionPerformed
               int id=0;
        boolean recogido=false;
        while(!recogido){
            String idSt = JOptionPane.showInputDialog(this, "Escriba la ID del empleado", "Eliminar empleado", JOptionPane.PLAIN_MESSAGE);
            if (idSt==null)
                return;
            try{
            id = Integer.parseInt(idSt);
            recogido=true;
            }catch(NumberFormatException ex){
            }
        }
        ResultadoOperacion r = Control.eliminarEmpleado(id);
        if (r.isOk()){
                JOptionPane.showMessageDialog(this, "Trabajo eliminado", "", JOptionPane.PLAIN_MESSAGE);
                actualizarTablas();
        }
        else{
                JOptionPane.showMessageDialog(this, r.getMsg(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miEliminarEmpleadoActionPerformed


    private void verPanel(String nombre){
    
    CardLayout layout = (CardLayout) panelPrincipal.getLayout();
    layout.show(panelPrincipal,nombre);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnAnadirEmpleado;
    private javax.swing.JButton btnAnadirTrabajo;
    private javax.swing.JButton btnAsignacionEmpleados;
    private javax.swing.JButton btnAsignacionTrabajos;
    private javax.swing.JButton btnEditarEmpleado;
    private javax.swing.JButton btnEditarTrabajo;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEliminarTrabajo;
    private javax.swing.JButton btnVerEmpleado;
    private javax.swing.JButton btnVerTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEmpleados;
    private javax.swing.JLabel lbEmpleadosEliminados;
    private javax.swing.JLabel lbTrabajos;
    private javax.swing.JLabel lbTrabajosEliminados;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mEmpleados;
    private javax.swing.JMenu mTrabajo;
    private javax.swing.JMenuItem miAnadirEmpleado;
    private javax.swing.JMenuItem miAnadirTrabajo;
    private javax.swing.JMenuItem miAsignarEmpleados;
    private javax.swing.JMenuItem miAsignarTrabajos;
    private javax.swing.JMenuItem miEditarEmpleado;
    private javax.swing.JMenuItem miEditarTrabajo;
    private javax.swing.JMenuItem miEliminarEmpleado;
    private javax.swing.JMenuItem miEliminarTrabajo;
    private javax.swing.JMenuItem miResetDatosIniciales;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miVerEmpleado;
    private javax.swing.JMenuItem miVerTodosEmpleados;
    private javax.swing.JMenuItem miVerTodosTrabajos;
    private javax.swing.JMenuItem miVerUnTrabajo;
    private javax.swing.JPanel panelEmpleado;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelEmpleadosOperaciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JPanel panelTrabajos;
    private javax.swing.JPanel panelTrabajosOperaciones;
    private javax.swing.JScrollPane scrollEmpleados;
    private javax.swing.JScrollPane scrollEmpleadosEliminados;
    private javax.swing.JScrollPane scrollTrabajos;
    private javax.swing.JScrollPane scrollTrabajosEliminados;
    private javax.swing.JTable tblEmpleadosActivos;
    private javax.swing.JTable tblEmpleadosBorrados;
    private javax.swing.JTable tblTrabajosActivos;
    private javax.swing.JTable tblTrabajosBorrados;
    // End of variables declaration//GEN-END:variables

    private void inicializarTablas() {
        //EMPLEADOS ACTIVOS
        EmpleadosTableModel tmEA = new EmpleadosTableModel(Control.getEmpleadosActivos());
        tblEmpleadosActivos.setModel(tmEA);
         //definir la tabla como no editable
        tblEmpleadosActivos.setEnabled(false);
        //crear sorter
        TableRowSorter<EmpleadosTableModel> rowSorterEA = new TableRowSorter<>(tmEA);
        tblEmpleadosActivos.setRowSorter(rowSorterEA);
        
        //ordenacion por defecto inicial
        List<SortKey> sortKeysEA = new ArrayList<>();
        sortKeysEA.add(new SortKey(0, SortOrder.ASCENDING));
        rowSorterEA.setSortKeys(sortKeysEA);

        //EMPLEADOS BORRADOS
        EmpleadosTableModel tmEB = new EmpleadosTableModel(Control.getEmpleadosBorrados());
        tblEmpleadosBorrados.setModel(tmEB);
         //definir la tabla como no editable
        tblEmpleadosBorrados.setEnabled(false);
        //crear sorter
        TableRowSorter<EmpleadosTableModel> rowSorterEB = new TableRowSorter<>(tmEB);
        tblTrabajosActivos.setRowSorter(rowSorterEB);
        
        //ordenacion por defecto inicial
        List<SortKey> sortKeysEB = new ArrayList<>();
        sortKeysEB.add(new SortKey(0, SortOrder.ASCENDING));
        rowSorterEB.setSortKeys(sortKeysEB);



        //TRABAJOS ACTIVOS
        TrabajosTableModel tmTA = new TrabajosTableModel(Control.getTrabajosActivos());
        tblTrabajosActivos.setModel(tmTA);
         //definir la tabla como no editable
        tblTrabajosActivos.setEnabled(false);
        //crear sorter
        TableRowSorter<TrabajosTableModel> rowSorterTA = new TableRowSorter<>(tmTA);
        tblTrabajosActivos.setRowSorter(rowSorterTA);
        
        //ordenacion por defecto inicial
        List<SortKey> sortKeysTA = new ArrayList<>();
        sortKeysTA.add(new SortKey(0, SortOrder.ASCENDING));
        rowSorterTA.setSortKeys(sortKeysTA);

        //TRABAJOS BORRADOS
        TrabajosTableModel tmTB = new TrabajosTableModel(Control.getTrabajosBorrados());
        tblTrabajosBorrados.setModel(tmTB);
         //definir la tabla como no editable
        tblTrabajosBorrados.setEnabled(false);
        //crear sorter
        TableRowSorter<TrabajosTableModel> rowSorterTB = new TableRowSorter<>(tmTB);
        tblTrabajosBorrados.setRowSorter(rowSorterTB);
        
        //ordenacion por defecto inicial
        List<SortKey> sortKeysTB = new ArrayList<>();
        sortKeysTB.add(new SortKey(0, SortOrder.ASCENDING));
        rowSorterTB.setSortKeys(sortKeysEB);

    }

    private void actualizarTablas() {
        actualizaTablasTrabajos();
        actualizaTablasEmpleados();
    }

    private void actualizaTablasEmpleados() {
        ((EmpleadosTableModel) tblEmpleadosActivos.getModel()).fireTableDataChanged();
        ((EmpleadosTableModel) tblEmpleadosBorrados.getModel()).fireTableDataChanged();
    }

    private void actualizaTablasTrabajos() {
        ((TrabajosTableModel) tblTrabajosActivos.getModel()).fireTableDataChanged();
        ((TrabajosTableModel) tblTrabajosBorrados.getModel()).fireTableDataChanged();
    }
}//fin VPrincipal15
