/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
Lista de paquetes:
 */
package ejercicio14.gui.dialogos;

import ejercicio14.dto.Empleado;
import ejercicio14.logica.ControlEmpleados;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Javier BO
 */
public class DEmpleado extends javax.swing.JDialog {

    /**
     * Tipos de uso del dialogo
     */
    public enum Tipo {
        VER,//para ver un empleado
        EDITAR,//para editar un empleado
        CREAR//para crear un empleado
    }

    private Tipo tipo;

    /**
     * Dialogo multifuncion para hacer operaciones sobre un empleado. Puede ser
     * usado crear un usuario, mostrar uno existente o editarlo.
     *
     * @param parent El Component padre
     * @param modal Si es modal o no
     * @param empleado Empleado a mostrar/editar. Si el tipo es crear no se
     * tendra en cuenta
     * @param tipo Tipo de uso del dialogo
     */
    public DEmpleado(java.awt.Frame parent, boolean modal, Empleado empleado, DEmpleado.Tipo tipo) {
        super(parent, modal);
        initComponents();

        //almacenar el tipo
        this.tipo = tipo;

        //inicializar segun el tipo
        switch (tipo) {
            case VER:
                inicializaVer(empleado);
                break;
            case EDITAR:
                inicializaEditar(empleado);
                break;
            case CREAR:
                inicializaCrear();
                break;
            default:
                throw new AssertionError();
        }

    }

    
    
    /**
     * Inicializacion del uso de crear empleado. 
     * Configura la interface ocultando los campos de id
     * haciendo editables los campos
     * y ajustando el texto del boton de guardar
     */
    private void inicializaCrear() {
        this.lbId.setVisible(false);
        this.campoId.setVisible(false);
        this.campoNombre.setEditable(true);
        this.campoDepartamento.setEditable(true);
        this.campoSueldo.setEditable(true);
        this.lbTitulo.setText("CREAR EMPLEADO");
    }

    
    
    /**
     * Inicializacion del uso de editar empleado. 
     * Configura la interface rellenando el formulario
     * haciendo editables los campos
     * y ajustando el texto del boton de guardar
     * 
     * @param empleado  Empleado a editar
     */
    private void inicializaEditar(Empleado empleado) {
        this.rellenarForumlario(empleado);
        this.campoNombre.setEditable(true);
        this.campoDepartamento.setEditable(true);
        this.campoSueldo.setEditable(true);
        this.lbTitulo.setText("EDITAR EMPLEADO");
    }

    
    /**
     * Inicializacion del uso de editar empleado. 
     * Configura la interface rellenando el formulario
     * haciendo NO editables los campos
     * y ajustando la visibilidad de botones
     * 
     * @param empleado Empleado a visualizar
     */
    private void inicializaVer(Empleado empleado) {
        this.rellenarForumlario(empleado);
        this.btnGuardar.setVisible(false);
        this.btnCancelar.setText("Cerrar");
        this.lbTitulo.setText("VER EMPLEADO");
    }

    
    /**
     * Rellena los campos con los datos de un empleado
     * @param empleado  El empleado a usar para rellenar los campos
     */
    private void rellenarForumlario(Empleado empleado) {
        campoId.setText("" + empleado.getId());
        campoNombre.setText(empleado.getNombre());
        campoDepartamento.setText("" + empleado.getDepartamento());
        campoSueldo.setText("" + empleado.getSueldo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbId = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbDepartamento = new javax.swing.JLabel();
        lbSueldo = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoDepartamento = new javax.swing.JTextField();
        campoSueldo = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lbId.setText("ID:");

        lbNombre.setText("NOMBRE:");

        lbDepartamento.setText("DEPARTAMENTO:");

        lbSueldo.setText("SUELDO:");

        campoId.setEditable(false);

        campoNombre.setEditable(false);

        campoDepartamento.setEditable(false);

        campoSueldo.setEditable(false);
        campoSueldo.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDepartamento)
                    .addComponent(lbId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSueldo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(campoDepartamento)
                    .addComponent(campoNombre)
                    .addComponent(campoId))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartamento)
                    .addComponent(campoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSueldo)
                    .addComponent(campoSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTitulo.setText("EMPLEADO");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Accion realizada al pulsar el boton de GUARDAR.
     * Recoge la informacion y la manda a ControlEmpleados
     *
     * @param evt
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int id = -1;
        String nombre = "";
        int departamento = 0;
        double sueldo = 0;
        
        //RECOGER ID. Si esta en modo editar no se habra rellenado
        //y la variable id se queda como -1
        try {
            id = Integer.parseInt(this.campoId.getText());
        } catch (NumberFormatException e) {
        }
        
        //RECOGER NOMBRE CON LIMITACION A 15 CARACTERES
        nombre = campoNombre.getText();
        if (nombre.length() < 1) {
            JOptionPane.showMessageDialog(this, "No puede dejar el nombre vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (nombre.length() > 15) {
            int opcion = JOptionPane.showConfirmDialog(this, "El nombre se recortará a 15 caracteres. ¿Está de acuerdo?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.NO_OPTION) {
                return;
            }
        }
        
        //RECOGER DEPARTAMENTO
        try {
            departamento = Integer.parseInt(this.campoDepartamento.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Departamento no válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //RECOGER SUELDO
        try {
            sueldo = Double.parseDouble(this.campoSueldo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Sueldo no válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //CREAR OBJETO EMPLEADO
        Empleado e = new Empleado(id, nombre, departamento, sueldo);
        
        //GUARDAR EMPLEADO
        ControlEmpleados.guardarEmpleado(e);
        
        //AVISO Y CIERRE
        JOptionPane.showMessageDialog(this, this.tipo == Tipo.CREAR ? "Empleado añadido" : "Empleado editado");
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Cierra el dialogo sin ejecutar ninguna accion
     *
     * @param evt
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoDepartamento;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoSueldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbDepartamento;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbSueldo;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables

}
