/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
Lista de paquetes:
 */

package ejercicio15.gui.dialogos;

import ejercicio15.dto.Empleado;
import ejercicio15.dto.Trabajo;
import ejercicio15.gui.tablemodels.TrabajosTableModel;
import ejercicio15.logica.Control;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jose Javier Bailon Ortiz
 */
public class DAsignTrabajosDeEmpleado extends javax.swing.JDialog {

    Empleado empleado;
    ArrayList<Trabajo> eSeleccionados;
    ArrayList<Trabajo> eNoSeleccionados;
    
    /**
     * 
     * @param parent
     * @param modal
     * @param empleado 
     */
    public DAsignTrabajosDeEmpleado(java.awt.Frame parent, boolean modal, Empleado empleado) {
        super(parent, modal);
        initComponents();
        this.empleado=empleado;
        lbIdEmpleado.setText("("+empleado.getId()+") "+empleado.getNombre()+" "+empleado.getApellidos());
        inicializarTablas();
        comprobarBotones();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        btnAsignar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        panelNoAsignados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoAsignados = new javax.swing.JTable();
        panelAsignados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAsignados = new javax.swing.JTable();
        lbAsignados = new javax.swing.JLabel();
        lbNoAsignados = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbIdEmpleado = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnAsignar.setText("ASIGNAR >>");
        btnAsignar.setActionCommand("ASIGNAR");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnQuitar.setText("<< QUITAR");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        panelNoAsignados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblNoAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNoAsignados);

        javax.swing.GroupLayout panelNoAsignadosLayout = new javax.swing.GroupLayout(panelNoAsignados);
        panelNoAsignados.setLayout(panelNoAsignadosLayout);
        panelNoAsignadosLayout.setHorizontalGroup(
            panelNoAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        panelNoAsignadosLayout.setVerticalGroup(
            panelNoAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        panelAsignados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAsignados);

        javax.swing.GroupLayout panelAsignadosLayout = new javax.swing.GroupLayout(panelAsignados);
        panelAsignados.setLayout(panelAsignadosLayout);
        panelAsignadosLayout.setHorizontalGroup(
            panelAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        panelAsignadosLayout.setVerticalGroup(
            panelAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lbAsignados.setText("EMPLEADOS ASIGNADOS");

        lbNoAsignados.setText("EMPLEADOS NO ASIGNADOS");

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addComponent(panelNoAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lbNoAsignados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAsignados)
                .addGap(125, 125, 125))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnAsignar)
                .addGap(33, 33, 33)
                .addComponent(btnQuitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAsignados)
                    .addComponent(lbNoAsignados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAsignados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNoAsignados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTitulo.setText("ASIGNACION DE TRABAJOS A EMPLEADO:");

        lbIdEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIdEmpleado.setText("5654");

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(lbIdEmpleado)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(lbIdEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int seleccionado=tblAsignados.getSelectedRow();
        if (seleccionado<0){
            JOptionPane.showMessageDialog(this, "Seleccione un trabajo de la tabla de asignados", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idTrabajoSeleccionado=tblAsignados.convertRowIndexToModel(seleccionado);
        idTrabajoSeleccionado= (int)tblAsignados.getModel().getValueAt(idTrabajoSeleccionado, 0);
        Control.desasignarTrabajoEnEmpleado(this.empleado.getId(), idTrabajoSeleccionado);
        Control.desasignarEmpleadoEnTrabajo(idTrabajoSeleccionado, this.empleado.getId());
        Trabajo trabajoAQuitar=null;
        for (Trabajo trabajo : eSeleccionados) {
            if (trabajo.getId()==idTrabajoSeleccionado){
                trabajoAQuitar=trabajo;
                break;
            }
        }
        
        eSeleccionados.remove(trabajoAQuitar);
        eNoSeleccionados.add(trabajoAQuitar);
        empleado=Control.getEmpleado(empleado.getId());
        actualizarTablas();
        comprobarBotones();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        int seleccionado=tblNoAsignados.getSelectedRow();
        if (seleccionado<0){
            JOptionPane.showMessageDialog(this, "Seleccione un trabajo de la tabla de no asignados", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idTrabajoSeleccionado=tblNoAsignados.convertRowIndexToModel(seleccionado);
        idTrabajoSeleccionado= (int)tblNoAsignados.getModel().getValueAt(idTrabajoSeleccionado, 0);
        Control.asignarTrabajoEnEmpleado(this.empleado.getId(), idTrabajoSeleccionado);
        Control.asignarEmpleadoEnTrabajo(idTrabajoSeleccionado, this.empleado.getId());
        Trabajo trabajoAPoner=null;
        for (Trabajo trabajo : eNoSeleccionados) {
            if (trabajo.getId()==idTrabajoSeleccionado){
                trabajoAPoner=trabajo;
                break;
            }
        }
        
        eNoSeleccionados.remove(trabajoAPoner);
        eSeleccionados.add(trabajoAPoner);
        empleado=Control.getEmpleado(empleado.getId());
        actualizarTablas();
        comprobarBotones();
    }//GEN-LAST:event_btnAsignarActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAsignados;
    private javax.swing.JLabel lbIdEmpleado;
    private javax.swing.JLabel lbNoAsignados;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelAsignados;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelNoAsignados;
    private javax.swing.JTable tblAsignados;
    private javax.swing.JTable tblNoAsignados;
    // End of variables declaration//GEN-END:variables

    private void inicializarTablas() {
        //recoger valores
        eSeleccionados=Control.getTrabajosEnEmpleado(empleado);
        eNoSeleccionados=Control.getTrabajosFueraDeEmpleado(empleado);
        
        //EMPLEADOS ASIGNADOS
        TrabajosTableModel tmEA = new TrabajosTableModel(eSeleccionados);
        tblAsignados.setModel(tmEA);
         //definir la tabla como seleccionable
        tblAsignados.setRowSelectionAllowed(true);
        tblAsignados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
        //crear sorter
        TableRowSorter<TrabajosTableModel> rowSorterEA = new TableRowSorter<>(tmEA);
        tblAsignados.setRowSorter(rowSorterEA);
        
        //ordenacion por defecto inicial
        List<RowSorter.SortKey> sortKeysEA = new ArrayList<>();
        sortKeysEA.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        rowSorterEA.setSortKeys(sortKeysEA);

        //EMPLEADOS NO ASIGNADOS
        TrabajosTableModel tmNA = new TrabajosTableModel(eNoSeleccionados);
        tblNoAsignados.setModel(tmNA);
         //definir la tabla como  seleccionable
        tblNoAsignados.setRowSelectionAllowed(true);
        tblAsignados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //crear sorter
        TableRowSorter<TrabajosTableModel> rowSorterEB = new TableRowSorter<>(tmNA);
        tblNoAsignados.setRowSorter(rowSorterEB);
        
        //ordenacion por defecto inicial
        List<RowSorter.SortKey> sortKeysEB = new ArrayList<>();
        sortKeysEB.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        rowSorterEB.setSortKeys(sortKeysEB);





    }

    private void actualizarTablas() {
        ((TrabajosTableModel) tblAsignados.getModel()).fireTableDataChanged();
        ((TrabajosTableModel) tblNoAsignados.getModel()).fireTableDataChanged();
    }

    private void comprobarBotones() {
        if (empleado.nTrabajosAsignados()<Empleado.limiteTrabajos)
            btnAsignar.setEnabled(true);
        else
            btnAsignar.setEnabled(false);
    }

}//fin DTrabajoAsignaciones
