/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
Lista de paquetes:
 */

package ejercicio15.gui.dialogos;

import ejercicio15.dto.Empleado;
import ejercicio15.dto.Trabajo;
import ejercicio15.gui.tablemodels.EmpleadosTableModel;
import ejercicio15.logica.Control;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 * Dialogo para la asignaciond de empleados a un trabajo
 * @author Jose Javier Bailon Ortiz
 */
public class DAsignEmpleadosDeTrabajo extends javax.swing.JDialog {
    //trabajo al que asignar
    Trabajo trabajo;
    //lista de empleados asignados
    ArrayList<Empleado> eSeleccionados;
    //lista de empleados candidatos para ser asignados
    ArrayList<Empleado> eNoSeleccionados;
    
    /**
     *  Constructor
     * @param parent
     * @param modal
     * @param trabajo 
     */
    public DAsignEmpleadosDeTrabajo(java.awt.Frame parent, boolean modal, Trabajo trabajo) {
        super(parent, modal);
        initComponents();
        //guardar referencia al trabajo
        this.trabajo=trabajo;
        //ajustar etiqueta de trabajo
        lbIdTrabajo.setText("("+trabajo.getId()+") "+trabajo.getNombre());
        
        inicializarTablas();
        comprobarBotones();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        btnAsignar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        panelNoAsignados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoAsignados = new javax.swing.JTable();
        panelAsignados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAsignados = new javax.swing.JTable();
        lbAsignados = new javax.swing.JLabel();
        lbNoAsignados = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbIdTrabajo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnAsignar.setText("ASIGNAR >>");
        btnAsignar.setActionCommand("ASIGNAR");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnQuitar.setText("<< QUITAR");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        panelNoAsignados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblNoAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNoAsignados);

        javax.swing.GroupLayout panelNoAsignadosLayout = new javax.swing.GroupLayout(panelNoAsignados);
        panelNoAsignados.setLayout(panelNoAsignadosLayout);
        panelNoAsignadosLayout.setHorizontalGroup(
            panelNoAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        panelNoAsignadosLayout.setVerticalGroup(
            panelNoAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        panelAsignados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAsignados);

        javax.swing.GroupLayout panelAsignadosLayout = new javax.swing.GroupLayout(panelAsignados);
        panelAsignados.setLayout(panelAsignadosLayout);
        panelAsignadosLayout.setHorizontalGroup(
            panelAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        panelAsignadosLayout.setVerticalGroup(
            panelAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lbAsignados.setText("EMPLEADOS ASIGNADOS");

        lbNoAsignados.setText("EMPLEADOS NO ASIGNADOS");

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addComponent(panelNoAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lbNoAsignados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAsignados)
                .addGap(125, 125, 125))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnAsignar)
                .addGap(33, 33, 33)
                .addComponent(btnQuitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAsignados)
                    .addComponent(lbNoAsignados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAsignados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNoAsignados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTitulo.setText("ASIGNACION DE EMPLEADOS A TRABAJO:");

        lbIdTrabajo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIdTrabajo.setText("5654");

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(lbIdTrabajo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(lbIdTrabajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boto cerrar
     * @param evt 
     */
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * Boton quitar empleado de trabajo
     * @param evt 
     */
    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        //recoger fila seleccionada
        int seleccionado=tblAsignados.getSelectedRow();
        if (seleccionado<0){
            JOptionPane.showMessageDialog(this, "Seleccione un empleado de la tabla de asignados", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idEmpleadoSeleccionado=tblAsignados.convertRowIndexToModel(seleccionado);
        idEmpleadoSeleccionado= (int)tblAsignados.getModel().getValueAt(idEmpleadoSeleccionado, 0);
        
        //eliminar la asignacion trabajo-empleado
        Control.desasignarEmpleadoEnTrabajo(this.trabajo.getId(), idEmpleadoSeleccionado);
        Control.desasignarTrabajoEnEmpleado(idEmpleadoSeleccionado, this.trabajo.getId());
        
        //actualizar listas del dialogo pertenecientes a cada tabla
        Empleado empleadoAQuitar=null;
        for (Empleado empleado : eSeleccionados) {
            if (empleado.getId()==idEmpleadoSeleccionado){
                empleadoAQuitar=empleado;
                break;
            }
        }
        eSeleccionados.remove(empleadoAQuitar);
        eNoSeleccionados.add(empleadoAQuitar);
        
        //refrescar referencia al trabajo
        trabajo=Control.getTrabajo(trabajo.getId());
        
        actualizarTablas();
        comprobarBotones();
    }//GEN-LAST:event_btnQuitarActionPerformed

    
    /**
     * Boton asigar empleado a trabajo
     * @param evt 
     */
    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed

        //recoger fila seleccionada
        int seleccionado=tblNoAsignados.getSelectedRow();
        if (seleccionado<0){
            JOptionPane.showMessageDialog(this, "Seleccione un empleado de la tabla de no asignados", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idEmpleadoSeleccionado=tblNoAsignados.convertRowIndexToModel(seleccionado);
        idEmpleadoSeleccionado= (int)tblNoAsignados.getModel().getValueAt(idEmpleadoSeleccionado, 0);
        
        //crear la asignacion trabajo-empleado
        Control.asignarEmpleadoEnTrabajo(this.trabajo.getId(), idEmpleadoSeleccionado);
        Control.asignarTrabajoEnEmpleado(idEmpleadoSeleccionado, this.trabajo.getId());
        
        //actualizar listas del dialogo pertenecientes a cada tabla
        Empleado empleadoAPoner=null;
        for (Empleado empleado : eNoSeleccionados) {
            if (empleado.getId()==idEmpleadoSeleccionado){
                empleadoAPoner=empleado;
                break;
            }
        }
        eNoSeleccionados.remove(empleadoAPoner);
        eSeleccionados.add(empleadoAPoner);
        
        //refrescar referencia al trabajo
        trabajo=Control.getTrabajo(trabajo.getId());
        
        actualizarTablas();
        comprobarBotones();
    }//GEN-LAST:event_btnAsignarActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAsignados;
    private javax.swing.JLabel lbIdTrabajo;
    private javax.swing.JLabel lbNoAsignados;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelAsignados;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelNoAsignados;
    private javax.swing.JTable tblAsignados;
    private javax.swing.JTable tblNoAsignados;
    // End of variables declaration//GEN-END:variables

    /**
     * Recoge los datos iniciales necesarios para las tablas y genera los tablemodels
     */
    private void inicializarTablas() {
        //recoger valores
        eSeleccionados=Control.getEmpleadosEnTrabajo(trabajo);
        eNoSeleccionados=Control.getEmpleadosFueraDeTrabajo(trabajo);
        
        //EMPLEADOS ASIGNADOS
        EmpleadosTableModel tmEA = new EmpleadosTableModel(eSeleccionados);
        tblAsignados.setModel(tmEA);
         //definir la tabla como seleccionable
        tblAsignados.setRowSelectionAllowed(true);
        tblAsignados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
        //crear sorter
        TableRowSorter<EmpleadosTableModel> rowSorterEA = new TableRowSorter<>(tmEA);
        tblAsignados.setRowSorter(rowSorterEA);
        
        //ordenacion por defecto inicial
        List<RowSorter.SortKey> sortKeysEA = new ArrayList<>();
        sortKeysEA.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        rowSorterEA.setSortKeys(sortKeysEA);

        
        
        //EMPLEADOS NO ASIGNADOS
        EmpleadosTableModel tmNA = new EmpleadosTableModel(eNoSeleccionados);
        tblNoAsignados.setModel(tmNA);
         //definir la tabla como  seleccionable
        tblNoAsignados.setRowSelectionAllowed(true);
        tblAsignados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //crear sorter
        TableRowSorter<EmpleadosTableModel> rowSorterEB = new TableRowSorter<>(tmNA);
        tblNoAsignados.setRowSorter(rowSorterEB);
        
        //ordenacion por defecto inicial
        List<RowSorter.SortKey> sortKeysEB = new ArrayList<>();
        sortKeysEB.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        rowSorterEB.setSortKeys(sortKeysEB);
    }

    
    /**
     * Refresca las tablas
     */
    private void actualizarTablas() {
        ((EmpleadosTableModel) tblAsignados.getModel()).fireTableDataChanged();
        ((EmpleadosTableModel) tblNoAsignados.getModel()).fireTableDataChanged();
    }

    /**
     * Comprueba si el trabajo ha llegado a su límite de empleados para en funcion
     * de eso habilitar o deshabilitar el boton de asignar
     */
    private void comprobarBotones() {
        if (trabajo.nEmpleadosAsignados()<Trabajo.limiteEmpleados)
            btnAsignar.setEnabled(true);
        else
            btnAsignar.setEnabled(false);
    }

}//fin DTrabajoAsignaciones
