/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
Lista de paquetes:
 */
package ejercicio15.gui.dialogos;

import ejercicio15.dto.Trabajo;
import ejercicio15.logica.Control;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Dialogo para crear y editar trabajos
 * @author Jose Javier Bailon Ortiz
 */
public class DCrearEditarTrabajo extends javax.swing.JDialog {

    /**
     * Posibles usos del dialogo
     */
    public enum Tipo {
        EDITAR,
        CREAR
    }
    
    //tipo de uso del dialogo (crear,editar)
    private Tipo tipo;

    /**
     * Constructor 
     * @param parent
     * @param modal
     * @param trabajo Trabajo a editar o null si es para crear
     * @param tipo Tipo de uso (crear, editar)
     */
    public DCrearEditarTrabajo(java.awt.Frame parent, boolean modal, Trabajo trabajo, DCrearEditarTrabajo.Tipo tipo) {
        super(parent, modal);
        initComponents();
        
        //guardar referencia al tipo de uso
        this.tipo = tipo;
        
        //inicializar segun el tipo de uso
        switch (tipo) {
            case EDITAR ->
                inicializaParaEditar(trabajo);
            case CREAR ->
                inicializaParaCrear();
            default ->
                throw new AssertionError();
        }
    }
    
    
    /**
     * Inicializacion para la creacion. Oculta el campo id y ajusta el texto
     * del boto de guardar
     */   
    private void inicializaParaCrear() {
        this.lbId.setVisible(false);
        this.inputId.setVisible(false);
        this.lbTitulo.setText("AÑADIR TRABAJO");
    }

     /**
     * Inicializacion para la edicion. Rellena los campos y ajusta el texto
     * del boto de guardar
     * @param empleado  Empleado a usar para rellenar los campos
     */
    private void inicializaParaEditar(Trabajo trabajo) {
        inputId.setText("" + trabajo.getId());
        inputNombre.setText(trabajo.getNombre());
        inputFecha.setValue(new Date(trabajo.getFecha()));
        this.lbTitulo.setText("EDITAR TRABAJO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCampos = new javax.swing.JPanel();
        lbId = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        inputFecha = new javax.swing.JSpinner();
        lbFecha = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbId.setText("ID");

        inputId.setEditable(false);

        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNombre.setText("NOMBRE");

        inputFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1700556587824L), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        javax.swing.JSpinner.DateEditor timeEditor = new javax.swing.JSpinner.DateEditor(inputFecha, "dd/MM/yyyy");
        inputFecha.setEditor(timeEditor);

        lbFecha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbFecha.setText("FECHA");

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputId, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(inputNombre))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFecha))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Trabajo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(52, 52, 52)
                .addComponent(btnCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     /**
     * Acciones para el boton de guardar. Recoge los datos y dependiendo del 
     * tipo de uso ordena a Control la creacion de un nuemo empleado o la actualizacion
     * de uno existente
     * @param evt 
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //recoger valores y validar
        int id = -1;
        String nombre;
        long fecha;
        //id
        try {
            id = Integer.parseInt(this.inputId.getText());
        } catch (NumberFormatException e) {
        }
        //nombre
        nombre = inputNombre.getText();
        if (nombre.length() < 1) {
            JOptionPane.showMessageDialog(this, "No puede dejar el nombre vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (nombre.length() > Trabajo.limiteNombre) {
            int opcion = JOptionPane.showConfirmDialog(this, "El nombre se recortará a 15 caracteres. ¿Está de acuerdo?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.NO_OPTION) {
                return;
            }
        }
        //fecha
        try {
            fecha = ((Date) this.inputFecha.getValue()).getTime();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Sueldo no válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //crear trabajo
        Trabajo t = new Trabajo(id, nombre, fecha, new int[Trabajo.limiteEmpleados]);
        
        //actuar segun el tipo de uso ordenando a control editar o crear
        switch (this.tipo) {
            case EDITAR -> Control.editarTrabajo(t);
            case CREAR -> Control.agregarTrabajo(t);
            default -> throw new AssertionError();
        }

        //aviso de resultado y cierre
        JOptionPane.showMessageDialog(this, this.tipo == Tipo.CREAR ? "Trabajo añadido" : "Trabajo editado");
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    
      
    /**
     * Cerrar diaologo
     * @param evt 
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JSpinner inputFecha;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelCampos;
    // End of variables declaration//GEN-END:variables

}//fin DTrabajo
